version: '3.1'

services:

  db:
    image: postgres:12.3
#    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432

  db2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
